// Dhanurmasa (Margazhi): the solar month of Dhanu, when Sri Andal's
// Tiruppavai is sung one pasuram a day before dawn. Day N of the month
// takes pasuram N; Koodaraivalli is the 27th and Bhogi — Sri Andal's
// Tirukalyanam — the last day.
import type { Named } from "./names";

const n = (en: string, kn: string): Named => ({ en, kn });

export type Pasuram = { tamil: string; kn: string; roman: string; gist: Named };

const p = (tamil: string, kn: string, roman: string, en: string, knGist: string): Pasuram => ({
  tamil,
  kn,
  roman,
  gist: n(en, knGist),
});

// The opening line of each of the thirty pasurams, with its theme.
export const TIRUPPAVAI: Pasuram[] = [
  p("மார்கழித் திங்கள் மதிநிறைந்த நன்னாளால்", "ಮಾರ್ಗಳಿತ್ ತಿಂಗಳ್ ಮದಿನಿರೈಂದ ನನ್ನಾಳಾಲ್", "mārgaḻit tiṅgaḷ madiniṟainda naṉṉāḷāl",
    "The call to the Margazhi vrata on this bright full-moon day: Narayana alone will grant us the drum (the boon).",
    "ಮಾರ್ಗಶಿರದ ಹುಣ್ಣಿಮೆಯ ಶುಭದಿನದಂದು ವ್ರತಕ್ಕೆ ಆಹ್ವಾನ — ನಾರಾಯಣನೇ ನಮಗೆ \"ಪರೈ\"ಯನ್ನು (ಅನುಗ್ರಹವನ್ನು) ಕೊಡುವವನು."),
  p("வையத்து வாழ்வீர்காள் நாமும் நம் பாவைக்கு", "ವೈಯತ್ತು ವಾಳ್ವೀರ್ಗಾಳ್ ನಾಮುಂ ನಂ ಪಾವೈಕ್ಕು", "vaiyattu vāḻvīrgāḷ nāmum nam pāvaikku",
    "The disciplines of the vrata — what to do and what to give up while singing the Lord's feet.",
    "ವ್ರತದ ನಿಯಮಗಳು — ಭಗವಂತನ ಪಾದಗಳನ್ನು ಹಾಡುತ್ತಾ ಏನು ಮಾಡಬೇಕು, ಏನನ್ನು ತ್ಯಜಿಸಬೇಕು."),
  p("ஓங்கி உலகளந்த உத்தமன் பேர்பாடி", "ಓಂಗಿ ಉಲಗಳಂದ ಉತ್ತಮನ್ ಪೇರ್ಪಾಡಿ", "ōṅgi ulagaḷanda uttamaṉ pērpāḍi",
    "Singing the name of Trivikrama who measured the worlds brings timely rain and plenty to the land.",
    "ಲೋಕಗಳನ್ನು ಅಳೆದ ತ್ರಿವಿಕ್ರಮನ ನಾಮವನ್ನು ಹಾಡಿದರೆ ಸಕಾಲಕ್ಕೆ ಮಳೆ, ನಾಡಿಗೆ ಸಮೃದ್ಧಿ."),
  p("ஆழி மழைக்கண்ணா ஒன்று நீ கை கரவேல்", "ಆಳಿ ಮಳೈಕ್ಕಣ್ಣಾ ಒನ್ರು ನೀ ಕೈ ಕರವೇಲ್", "āḻi maḻaikkaṇṇā oṉṟu nī kai karavēl",
    "A prayer to the rain-god to rise dark as the Lord, flash like His discus, roar like His conch and pour like His arrows.",
    "ಮಳೆದೇವನಿಗೆ ಪ್ರಾರ್ಥನೆ — ಭಗವಂತನಂತೆ ಕಪ್ಪಾಗಿ, ಅವನ ಚಕ್ರದಂತೆ ಮಿಂಚಿ, ಶಂಖದಂತೆ ಗುಡುಗಿ, ಬಾಣಗಳಂತೆ ಮಳೆಗರೆ."),
  p("மாயனை மன்னு வடமதுரை மைந்தனை", "ಮಾಯನೈ ಮನ್ನು ವಡಮದುರೈ ಮೈಂದನೈ", "māyaṉai maṉṉu vaḍamadurai maindaṉai",
    "Singing Damodara's names with a pure heart burns away past and future sins like cotton in fire.",
    "ಶುದ್ಧ ಮನಸ್ಸಿನಿಂದ ದಾಮೋದರನ ನಾಮಗಳನ್ನು ಹಾಡಿದರೆ ಹಿಂದಿನ-ಮುಂದಿನ ಪಾಪಗಳು ಬೆಂಕಿಯಲ್ಲಿ ಹತ್ತಿಯಂತೆ ಸುಟ್ಟುಹೋಗುತ್ತವೆ."),
  p("புள்ளும் சிலம்பின காண் புள்ளரையன் கோயிலில்", "ಪುಳ್ಳುಂ ಸಿಲಂಬಿನ ಕಾಣ್ ಪುಳ್ಳರೈಯನ್ ಕೋಯಿಲಿಲ್", "puḷḷum silambiṉa kāṇ puḷḷaraiyaṉ kōyilil",
    "The waking begins: birds are calling and the temple conch sounds — wake, young girl, and join us.",
    "ಎಬ್ಬಿಸುವ ಪಾಶುರಗಳ ಆರಂಭ — ಹಕ್ಕಿಗಳು ಕೂಗುತ್ತಿವೆ, ದೇವಾಲಯದ ಶಂಖ ಮೊಳಗುತ್ತಿದೆ; ಎದ್ದು ನಮ್ಮೊಡನೆ ಬಾ."),
  p("கீசு கீசு என்று எங்கும் ஆனைச்சாத்தன்", "ಕೀಸು ಕೀಸು ಎನ್ರು ಎಂಗುಂ ಆನೈಚ್ಚಾತ್ತನ್", "kīsu kīsu eṉṟu eṅgum āṉaiccāttaṉ",
    "The birds chatter and the churning of curd fills the air — how can you sleep while we sing of Keshava?",
    "ಹಕ್ಕಿಗಳ ಚಿಲಿಪಿಲಿ, ಮೊಸರು ಕಡೆಯುವ ಸದ್ದು — ನಾವು ಕೇಶವನನ್ನು ಹಾಡುತ್ತಿರುವಾಗ ನೀನು ಹೇಗೆ ಮಲಗಿರುವೆ?"),
  p("கீழ்வானம் வெள்ளென்று எருமை சிறுவீடு", "ಕೀಳ್ವಾನಂ ವೆಳ್ಳೆನ್ರು ಎರುಮೈ ಸಿರುವೀಡು", "kīḻvāṉam veḷḷeṉṟu erumai siṟuvīḍu",
    "The eastern sky grows white and the buffaloes go out to graze — rise, joyful one, the Lord awaits.",
    "ಪೂರ್ವದ ಆಕಾಶ ಬೆಳ್ಳಗಾಗಿದೆ, ಎಮ್ಮೆಗಳು ಮೇಯಲು ಹೊರಟಿವೆ — ಏಳು, ಭಗವಂತ ಕಾಯುತ್ತಿದ್ದಾನೆ."),
  p("தூமணி மாடத்துச் சுற்றும் விளக்கெரிய", "ತೂಮಣಿ ಮಾಡತ್ತುಚ್ ಚುಟ್ರುಂ ವಿಳಕ್ಕೆರಿಯ", "tūmaṇi māḍattuc cuṟṟum viḷakkeriya",
    "To the girl asleep in the lamp-lit jewelled mansion: aunt, wake your daughter to sing the Lord's many names.",
    "ದೀಪ ಬೆಳಗುವ ರತ್ನಮಯ ಮಹಲಿನಲ್ಲಿ ಮಲಗಿರುವವಳಿಗೆ — ಅತ್ತೆ, ಭಗವಂತನ ನಾಮಗಳನ್ನು ಹಾಡಲು ನಿನ್ನ ಮಗಳನ್ನು ಎಬ್ಬಿಸು."),
  p("நோற்றுச் சுவர்க்கம் புகுகின்ற அம்மனாய்", "ನೋಟ್ರುಚ್ ಚುವರ್ಕ್ಕಂ ಪುಗುಗಿನ್ರ ಅಮ್ಮನಾಯ್", "nōṟṟuc cuvarkkam pugugiṉṟa ammaṉāy",
    "To one who seems to have earned heaven by her penance and will not even answer the door — open it!",
    "ತಪಸ್ಸಿನಿಂದ ಸ್ವರ್ಗ ಸೇರಿದವಳಂತೆ ಬಾಗಿಲನ್ನೂ ತೆರೆಯದೆ ಉತ್ತರಿಸದವಳಿಗೆ — ಬಾಗಿಲು ತೆರೆ!"),
  p("கற்றுக் கறவைக் கணங்கள் பல கறந்து", "ಕಟ್ರುಕ್ ಕರವೈಕ್ ಕಣಂಗಳ್ ಪಲ ಕರಂದು", "kaṟṟuk kaṟavaik kaṇaṅgaḷ pala kaṟandu",
    "To the golden creeper of the faultless cowherd clan: all your friends are here singing of the cloud-hued Lord.",
    "ದೋಷರಹಿತ ಗೋಪಕುಲದ ಸ್ವರ್ಣಲತೆಗೆ — ನಿನ್ನ ಗೆಳತಿಯರೆಲ್ಲ ಮೇಘವರ್ಣನನ್ನು ಹಾಡುತ್ತಾ ಬಂದಿದ್ದಾರೆ."),
  p("கனைத்திளம் கற்றெருமை கன்றுக்கு இரங்கி", "ಕನೈತ್ತಿಳಂ ಕಟ್ರೆರುಮೈ ಕನ್ರುಕ್ಕು ಇರಂಗಿ", "kaṉaittiḷam kaṟṟerumai kaṉṟukku iraṅgi",
    "To the sister of the cowherd whose buffaloes overflow with milk: we stand in the dew singing of Rama — wake!",
    "ಹಾಲು ಉಕ್ಕುವ ಎಮ್ಮೆಗಳ ಗೋಪನ ತಂಗಿಗೆ — ಮಂಜಿನಲ್ಲಿ ನಿಂತು ರಾಮನನ್ನು ಹಾಡುತ್ತಿದ್ದೇವೆ, ಏಳು!"),
  p("புள்ளின்வாய் கீண்டானைப் பொல்லா அரக்கனை", "ಪುಳ್ಳಿನ್ವಾಯ್ ಕೀಂಡಾನೈಪ್ ಪೊಲ್ಲಾ ಅರಕ್ಕನೈ", "puḷḷiṉvāy kīṇḍāṉaip pollā arakkaṉai",
    "Venus has risen and Jupiter set — all the girls have gone to the vrata grounds; don't miss this good day.",
    "ಶುಕ್ರ ಉದಯಿಸಿ ಗುರು ಅಸ್ತಮಿಸಿದ್ದಾನೆ — ಎಲ್ಲರೂ ವ್ರತಸ್ಥಳಕ್ಕೆ ಹೊರಟಿದ್ದಾರೆ; ಈ ಶುಭದಿನವನ್ನು ತಪ್ಪಿಸಿಕೊಳ್ಳಬೇಡ."),
  p("உங்கள் புழைக்கடைத் தோட்டத்து வாவியுள்", "ಉಂಗಳ್ ಪುಳೈಕ್ಕಡೈತ್ ತೋಟ್ಟತ್ತು ವಾವಿಯುಳ್", "uṅgaḷ puḻaikkaḍait tōṭṭattu vāviyuḷ",
    "To the girl who promised to wake us all: the lilies in your garden pond have opened — rise and keep your word.",
    "ಎಲ್ಲರನ್ನೂ ಎಬ್ಬಿಸುವೆನೆಂದು ಮಾತು ಕೊಟ್ಟವಳಿಗೆ — ನಿನ್ನ ತೋಟದ ಕೊಳದ ನೈದಿಲೆಗಳು ಅರಳಿವೆ; ಎದ್ದು ಮಾತು ಉಳಿಸಿಕೋ."),
  p("எல்லே இளங்கிளியே இன்னம் உறங்குதியோ", "ಎಲ್ಲೇ ಇಳಂಗಿಳಿಯೇ ಇನ್ನಂ ಉರಂಗುದಿಯೋ", "ellē iḷaṅgiḷiyē iṉṉam uṟaṅgudiyō",
    "\"O young parrot, still asleep?\" — a playful exchange, and she humbly takes the blame and joins.",
    "\"ಓ ಎಳೆಯ ಗಿಳಿಯೇ, ಇನ್ನೂ ಮಲಗಿರುವೆಯಾ?\" — ವಿನೋದದ ಸಂವಾದ; ಅವಳು ವಿನಯದಿಂದ ತಪ್ಪೊಪ್ಪಿ ಸೇರುತ್ತಾಳೆ."),
  p("நாயகனாய் நின்ற நந்தகோபனுடைய", "ನಾಯಗನಾಯ್ ನಿನ್ರ ನಂದಗೋಪನುಡೈಯ", "nāyagaṉāy niṉṟa nandagōpaṉuḍaiya",
    "At Nandagopa's palace: guardian of the gate, open the door — we come pure, to wake the Lord with song.",
    "ನಂದಗೋಪನ ಅರಮನೆಯ ಬಾಗಿಲಲ್ಲಿ — ದ್ವಾರಪಾಲಕನೇ, ಬಾಗಿಲು ತೆರೆ; ಶುದ್ಧರಾಗಿ ಭಗವಂತನನ್ನು ಹಾಡಿ ಎಬ್ಬಿಸಲು ಬಂದಿದ್ದೇವೆ."),
  p("அம்பரமே தண்ணீரே சோறே அறம் செய்யும்", "ಅಂಬರಮೇ ತಣ್ಣೀರೇ ಸೋರೇ ಅರಂ ಸೆಯ್ಯುಂ", "ambaramē taṇṇīrē sōṟē aṟam seyyum",
    "Waking Nandagopa who gives cloth, water and food, Yashoda, Krishna and Balarama in turn.",
    "ವಸ್ತ್ರ, ನೀರು, ಅನ್ನ ದಾನ ಮಾಡುವ ನಂದಗೋಪ, ಯಶೋದೆ, ಕೃಷ್ಣ ಮತ್ತು ಬಲರಾಮರನ್ನು ಕ್ರಮವಾಗಿ ಎಬ್ಬಿಸುವುದು."),
  p("உந்து மதகளிற்றன் ஓடாத தோள்வலியன்", "ಉಂದು ಮದಗಳಿಟ್ರನ್ ಓಡಾದ ತೋಳ್ವಲಿಯನ್", "undu madagaḷiṟṟaṉ ōḍāda tōḷvaliyaṉ",
    "To Nappinnai, Nandagopa's daughter-in-law with fragrant hair: the cocks crow — open the door with your bangled hands.",
    "ಸುಗಂಧ ಕೇಶದ ನಂದಗೋಪನ ಸೊಸೆ ನಪ್ಪಿನ್ನೈಗೆ — ಕೋಳಿಗಳು ಕೂಗುತ್ತಿವೆ; ಬಳೆಯ ಕೈಗಳಿಂದ ಬಾಗಿಲು ತೆರೆ."),
  p("குத்து விளக்கெரியக் கோட்டுக்கால் கட்டில்மேல்", "ಕುತ್ತು ವಿಳಕ್ಕೆರಿಯಕ್ ಕೋಟ್ಟುಕ್ಕಾಲ್ ಕಟ್ಟಿಲ್ಮೇಲ್", "kuttu viḷakkeriyak kōṭṭukkāl kaṭṭilmēl",
    "Nappinnai and Krishna on the ivory couch by the standing lamp — do not keep Him from us even a moment.",
    "ದೀಪ ಬೆಳಗುವ ದಂತದ ಮಂಚದ ಮೇಲೆ ನಪ್ಪಿನ್ನೈ ಮತ್ತು ಕೃಷ್ಣ — ಕ್ಷಣಕಾಲವೂ ಅವನನ್ನು ನಮ್ಮಿಂದ ದೂರವಿಡಬೇಡ."),
  p("முப்பத்து மூவர் அமரர்க்கு முன்சென்று", "ಮುಪ್ಪತ್ತು ಮೂವರ್ ಅಮರರ್ಕ್ಕು ಮುನ್ಸೆನ್ರು", "muppattu mūvar amararkku muṉseṉṟu",
    "To the Lord who frees the thirty-three gods from fear, and to Nappinnai: give us the mirror and fan, and the Lord, for our bath.",
    "ಮೂವತ್ತುಮೂರು ದೇವತೆಗಳ ಭಯ ನೀಗಿಸುವವನಿಗೆ ಮತ್ತು ನಪ್ಪಿನ್ನೈಗೆ — ಕನ್ನಡಿ, ಬೀಸಣಿಗೆ ಹಾಗೂ ಭಗವಂತನನ್ನೇ ನಮಗೆ ಕೊಡು."),
  p("ஏற்ற கலங்கள் எதிர்பொங்கி மீதளிப்ப", "ಏಟ್ರ ಕಲಂಗಳ್ ಎದಿರ್ಪೊಂಗಿ ಮೀದಳಿಪ್ಪ", "ēṟṟa kalaṅgaḷ edirpoṅgi mīdaḷippa",
    "Son of the one whose cows fill every vessel to overflowing: we come like defeated foes, to praise Your feet.",
    "ಪಾತ್ರೆಗಳು ಉಕ್ಕುವಂತೆ ಹಾಲು ಕರೆಯುವ ಹಸುಗಳ ಒಡೆಯನ ಮಗನೇ — ಸೋತ ಶತ್ರುಗಳಂತೆ ನಿನ್ನ ಪಾದಗಳನ್ನು ಸ್ತುತಿಸಲು ಬಂದಿದ್ದೇವೆ."),
  p("அங்கண் மா ஞாலத்து அரசர் அபிமான", "ಅಂಗಣ್ ಮಾ ಞಾಲತ್ತು ಅರಸರ್ ಅಭಿಮಾನ", "aṅgaṇ mā ñālattu arasar abimāṉa",
    "Like kings who lay down their pride at Your bedside, we have come — turn Your lotus eyes slowly upon us.",
    "ಅಹಂಕಾರ ತೊರೆದು ನಿನ್ನ ಮಂಚದ ಬಳಿ ನಿಂತ ರಾಜರಂತೆ ನಾವು ಬಂದಿದ್ದೇವೆ — ನಿನ್ನ ಕಮಲನೇತ್ರಗಳಿಂದ ನಿಧಾನವಾಗಿ ನಮ್ಮನ್ನು ನೋಡು."),
  p("மாரிமலை முழைஞ்சில் மன்னிக் கிடந்துறங்கும்", "ಮಾರಿಮಲೈ ಮುಳೈಂಜಿಲ್ ಮನ್ನಿಕ್ ಕಿಡಂದುರಂಗುಂ", "mārimalai muḻaiñcil maṉṉik kiḍanduṟaṅgum",
    "Rise like a lion waking in its mountain cave, come to Your throne, and hear why we have come.",
    "ಬೆಟ್ಟದ ಗುಹೆಯಲ್ಲಿ ಎಚ್ಚರಗೊಳ್ಳುವ ಸಿಂಹದಂತೆ ಎದ್ದು ಸಿಂಹಾಸನಕ್ಕೆ ಬಂದು ನಾವು ಬಂದ ಕಾರಣವನ್ನು ಕೇಳು."),
  p("அன்று இவ்வுலகம் அளந்தாய் அடிபோற்றி", "ಅನ್ರು ಇವ್ವುಲಗಂ ಅಳಂದಾಯ್ ಅಡಿಪೋಟ್ರಿ", "aṉṟu ivvulagam aḷandāy aḍipōṟṟi",
    "Hail to Your feet that measured the worlds, to Your valour, Your fame, Your anklets, Your spear — we come to receive the drum.",
    "ಲೋಕಗಳನ್ನು ಅಳೆದ ನಿನ್ನ ಪಾದಗಳಿಗೆ, ಪರಾಕ್ರಮಕ್ಕೆ, ಕೀರ್ತಿಗೆ, ಗೆಜ್ಜೆಗಳಿಗೆ, ಆಯುಧಕ್ಕೆ ಮಂಗಳ — \"ಪರೈ\" ಪಡೆಯಲು ಬಂದಿದ್ದೇವೆ."),
  p("ஒருத்தி மகனாய்ப் பிறந்து ஓர் இரவில்", "ಒರುತ್ತಿ ಮಗನಾಯ್ಪ್ ಪಿರಂದು ಓರ್ ಇರವಿಲ್", "orutti magaṉāyp piṟandu ōr iravil",
    "Born to one mother, raised that very night by another — we come seeking You, and our sorrows are gone.",
    "ಒಬ್ಬಳ ಮಗನಾಗಿ ಹುಟ್ಟಿ ಅದೇ ರಾತ್ರಿ ಇನ್ನೊಬ್ಬಳ ಮಗನಾಗಿ ಬೆಳೆದವನೇ — ನಿನ್ನನ್ನು ಹುಡುಕಿ ಬಂದೆವು, ನಮ್ಮ ದುಃಖ ದೂರವಾಯಿತು."),
  p("மாலே மணிவண்ணா மார்கழி நீராடுவான்", "ಮಾಲೇ ಮಣಿವಣ್ಣಾ ಮಾರ್ಗಳಿ ನೀರಾಡುವಾನ್", "mālē maṇivaṇṇā mārgaḻi nīrāḍuvāṉ",
    "For the Margazhi bath we ask for conches like Your Panchajanya, great drums, singers, lamps, banners and a canopy.",
    "ಮಾರ್ಗಶಿರ ಸ್ನಾನಕ್ಕಾಗಿ ಪಾಂಚಜನ್ಯದಂತಹ ಶಂಖಗಳು, ಡೋಲುಗಳು, ಹಾಡುಗಾರರು, ದೀಪಗಳು, ಧ್ವಜಗಳು ಮತ್ತು ಮೇಲ್ಕಟ್ಟು ಬೇಡುತ್ತೇವೆ."),
  p("கூடாரை வெல்லும் சீர்க் கோவிந்தா உன்தன்னைப்", "ಕೂಡಾರೈ ವೆಲ್ಲುಂ ಸೀರ್ಕ್ ಕೋವಿಂದಾ ಉನ್ದನ್ನೈಪ್", "kūḍārai vellum sīrk kōvindā uṉtaṉṉaip",
    "Koodaraivalli: Govinda who wins over even those who stay away — adorned by You, we shall feast together on rice swimming in ghee.",
    "ಕೂಡಾರೈವಳ್ಳಿ: ದೂರವಿರುವವರನ್ನೂ ಗೆಲ್ಲುವ ಗೋವಿಂದ — ನಿನ್ನಿಂದ ಅಲಂಕೃತರಾಗಿ ತುಪ್ಪದಲ್ಲಿ ಮುಳುಗಿದ ಅನ್ನವನ್ನು ಒಟ್ಟಾಗಿ ಸವಿಯುವೆವು."),
  p("கறவைகள் பின்சென்று கானம் சேர்ந்து உண்போம்", "ಕರವೈಗಳ್ ಪಿನ್ಸೆನ್ರು ಕಾನಂ ಸೇರ್ಂದು ಉಣ್ಬೋಂ", "kaṟavaigaḷ piṉseṉṟu kāṉam sērndu uṇbōm",
    "We are simple cowherds who follow the cows to the forest; our bond with You can never be broken — forgive our familiarity.",
    "ಹಸುಗಳ ಹಿಂದೆ ಕಾಡಿಗೆ ಹೋಗುವ ಮುಗ್ಧ ಗೋಪಿಯರು ನಾವು; ನಿನ್ನೊಡನೆ ನಮ್ಮ ಸಂಬಂಧ ಎಂದಿಗೂ ಮುರಿಯದು — ನಮ್ಮ ಸಲಿಗೆಯನ್ನು ಕ್ಷಮಿಸು."),
  p("சிற்றஞ் சிறுகாலே வந்துன்னைச் சேவித்து", "ಸಿಟ್ರಂ ಸಿರುಕಾಲೇ ವಂದುನ್ನೈಚ್ ಚೇವಿತ್ತು", "ciṟṟañ ciṟukālē vanduṉṉaic cēvittu",
    "Not the drum alone: through seven times seven births we wish only to belong to You and serve You — remove all other desires.",
    "ಕೇವಲ \"ಪರೈ\" ಅಲ್ಲ — ಏಳೇಳು ಜನ್ಮಗಳಲ್ಲೂ ನಿನಗೆ ಸೇರಿದವರಾಗಿ ನಿನ್ನ ಸೇವೆ ಮಾಡುವುದೊಂದೇ ಬಯಕೆ; ಉಳಿದ ಆಸೆಗಳನ್ನು ಹೋಗಲಾಡಿಸು."),
  p("வங்கக் கடல் கடைந்த மாதவனைக் கேசவனை", "ವಂಗಕ್ ಕಡಲ್ ಕಡೈಂದ ಮಾಧವನೈಕ್ ಕೇಶವನೈ", "vaṅgak kaḍal kaḍainda mādhavaṉaik kēsavaṉai",
    "Phala shruti: whoever sings these thirty verses of Andal, daughter of Periyalwar of Srivilliputtur, will be blessed by Tirumal everywhere.",
    "ಫಲಶ್ರುತಿ: ಶ್ರೀವಿಲ್ಲಿಪುತ್ತೂರಿನ ಪೆರಿಯಾಳ್ವಾರರ ಮಗಳು ಆಂಡಾಳಳ ಈ ಮೂವತ್ತು ಪಾಶುರಗಳನ್ನು ಹಾಡುವವರು ಎಲ್ಲೆಡೆ ತಿರುಮಾಲನ ಕೃಪೆಗೆ ಪಾತ್ರರಾಗುವರು."),
];

export const DHANURMASA = {
  name: n("Dhanurmasa", "ಧನುರ್ಮಾಸ"),
  begins: n("Dhanurmasa begins", "ಧನುರ್ಮಾಸ ಆರಂಭ"),
  koodaraivalli: n("Koodaraivalli (Tiruppavai 27)", "ಕೂಡಾರೈವಳ್ಳಿ (ತಿರುಪ್ಪಾವೈ 27)"),
  bhogi: n("Bhogi · Sri Andal Tirukalyanam", "ಭೋಗಿ · ಶ್ರೀ ಆಂಡಾಳ್ ತಿರುಕಲ್ಯಾಣ"),
  about: n(
    "The holiest month for Srivaishnavas. Sri Andal's Tiruppavai is sung before dawn, one pasuram each day, with Dhanurmasa pooja in the Brahma muhurta and pongal offered as naivedya. At Tirumala, Tiruppavai replaces the Suprabhatam this month.",
    "ಶ್ರೀವೈಷ್ಣವರಿಗೆ ಅತ್ಯಂತ ಪವಿತ್ರ ಮಾಸ. ಪ್ರತಿದಿನ ಬೆಳಗಿನ ಜಾವ ಶ್ರೀ ಆಂಡಾಳರ ತಿರುಪ್ಪಾವೈಯ ಒಂದೊಂದು ಪಾಶುರವನ್ನು ಹಾಡಲಾಗುತ್ತದೆ; ಬ್ರಾಹ್ಮೀ ಮುಹೂರ್ತದಲ್ಲಿ ಧನುರ್ಮಾಸ ಪೂಜೆ, ಪೊಂಗಲ್ ನೈವೇದ್ಯ. ಈ ತಿಂಗಳು ತಿರುಮಲದಲ್ಲಿ ಸುಪ್ರಭಾತದ ಬದಲು ತಿರುಪ್ಪಾವೈ ಪಠಣ.",
  ),
};
